// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5LBdKSOXdGJ66Bf84FmsZuW2eL9G8iM',
    appId: '1:533961426623:web:ebe735b9e8a36ec21ee80a',
    messagingSenderId: '533961426623',
    projectId: 'ottug-i-curry',
    authDomain: 'ottug-i-curry.firebaseapp.com',
    storageBucket: 'ottug-i-curry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGuetxgYzYzmyKWL48ujif7UrdsQ33cs',
    appId: '1:533961426623:android:46684aa785a626a71ee80a',
    messagingSenderId: '533961426623',
    projectId: 'ottug-i-curry',
    storageBucket: 'ottug-i-curry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVWXCQtvvrrOqYkOlAPt8TluIjBUzlD0',
    appId: '1:533961426623:ios:ecc349b86dbbc8061ee80a',
    messagingSenderId: '533961426623',
    projectId: 'ottug-i-curry',
    storageBucket: 'ottug-i-curry.appspot.com',
    androidClientId: '533961426623-jhj5eu1m06rkdavg5ca1p38g0ol3j7mh.apps.googleusercontent.com',
    iosClientId: '533961426623-17qecigrqom78pqt8ts3p5kccjb1d6ns.apps.googleusercontent.com',
    iosBundleId: 'com.ottugi.curry.ottugiCurry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVWXCQtvvrrOqYkOlAPt8TluIjBUzlD0',
    appId: '1:533961426623:ios:ecc349b86dbbc8061ee80a',
    messagingSenderId: '533961426623',
    projectId: 'ottug-i-curry',
    storageBucket: 'ottug-i-curry.appspot.com',
    androidClientId: '533961426623-jhj5eu1m06rkdavg5ca1p38g0ol3j7mh.apps.googleusercontent.com',
    iosClientId: '533961426623-17qecigrqom78pqt8ts3p5kccjb1d6ns.apps.googleusercontent.com',
    iosBundleId: 'com.ottugi.curry.ottugiCurry',
  );
}
